2020-01-13 13:32:02,726 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:35]
2020-01-13 13:57:39,199 ERROR: Exception on /dashboard [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
pyodbc.OperationalError: ('08S01', '[08S01] [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x20 (32) (SQLExecDirectW)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 259, in decorated_view
    elif not current_user.is_authenticated:
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/local.py", line 348, in __getattr__
    return getattr(self._get_current_object(), name)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/local.py", line 307, in _get_current_object
    return self.__local()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 26, in <lambda>
    current_user = LocalProxy(lambda: _get_user())
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 335, in _get_user
    current_app.login_manager._load_user()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/login_manager.py", line 359, in _load_user
    return self.reload_user()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/login_manager.py", line 321, in reload_user
    user = self.user_callback(user_id)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/models.py", line 23, in load_user
    return User.query.get(int(id))
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 982, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 1094, in _get_impl
    return db_load_fn(self, primary_key_identity)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/loading.py", line 284, in load_on_pk_identity
    return q.one()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3325, in one
    ret = self.one_or_none()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3294, in one_or_none
    ret = list(self)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3367, in __iter__
    return self._execute_and_instances(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3392, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 982, in execute
    return meth(self, multiparams, params)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1101, in _execute_clauseelement
    distilled_params,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1250, in _execute_context
    e, statement, parameters, cursor, context
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1476, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1246, in _execute_context
    cursor, statement, parameters, context
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 581, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (pyodbc.OperationalError) ('08S01', '[08S01] [Microsoft][ODBC Driver 13 for SQL Server]TCP Provider: Error code 0x20 (32) (SQLExecDirectW)')
[SQL: SELECT [User].id AS [User_id], [User].username AS [User_username], [User].email AS [User_email], [User].password_hash AS [User_password_hash] 
FROM [User] 
WHERE [User].id = ?]
[parameters: (2,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2020-01-13 20:26:00,570 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:28:18,718 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:33:00,082 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:35:00,089 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:37:32,622 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:42:01,372 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:43:46,011 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:44:32,022 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 20:55:42,189 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:11:15,199 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:12:06,397 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:14:32,449 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:28:18,757 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:30:46,580 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:36:10,804 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:42:29,775 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:44:02,476 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:44:48,578 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:47:33,145 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:51:58,388 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 21:52:37,250 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 22:10:43,109 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 22:13:38,478 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-13 22:13:59,293 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-14 19:34:38,909 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-14 21:29:14,598 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-14 21:51:56,615 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
