2020-01-09 10:07:53,861 ERROR: Exception on /video_feed [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 35, in video_feed
    return Response(gen(camera),
NameError: name 'gen' is not defined
2020-01-09 10:11:34,666 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:11:41,389 ERROR: Exception on /video_feed [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 51, in video_feed
    return Response(gen(camera),
NameError: name 'camera' is not defined
2020-01-09 10:12:43,583 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:14:17,479 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:15:09,029 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:15:45,892 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:16:17,170 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:16:49,092 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:18:37,154 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:30:51,279 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:31:06,484 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:31:35,191 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 10:32:17,934 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 11:51:29,146 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:38]
2020-01-09 12:16:00,761 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:31]
2020-01-09 12:16:32,497 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:31]
2020-01-09 12:16:35,977 ERROR: Exception on /index [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 52, in index
    return render_template('index.html', title='Home')
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 48, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/index.html", line 25, in block "app_content"
    <img src="{{ url_for('video_feed') }}">
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'video_feed'. Did you mean 'index' instead?
2020-01-09 12:16:58,851 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:31]
