2020-01-16 21:43:32,265 ERROR: Exception on /output [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 137, in output
    return render_template('output.html')
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/output.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/output.html", line 12, in block "content"
    <button onclick="window.location.href = '{{ url_for('startRecognize') }}'" type="submit"
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_azure_storage.py", line 45, in url_for
    return flask_url_for(endpoint, **values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'startRecognize'. Did you mean 'static' instead?
2020-01-16 21:45:00,552 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
2020-01-16 21:45:06,912 ERROR: Exception on /output [GET] [in /Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/routes.py", line 137, in output
    return render_template('output.html')
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/output.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/application/templates/output.html", line 12, in block "content"
    <button onclick="window.location.href = '{{ url_for('startRecognize') }}'" type="submit"
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask_azure_storage.py", line 45, in url_for
    return flask_url_for(endpoint, **values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 370, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/app.py", line 2215, in handle_url_build_error
    reraise(exc_type, exc_value, tb)
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/flask/helpers.py", line 358, in url_for
    endpoint, values, method=method, force_external=external
  File "/Users/wouterlefebvre/Github Repo's/FaceRec/FaceRecVenv/lib/python3.6/site-packages/werkzeug/routing.py", line 2020, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'startRecognize'. Did you mean 'static' instead?
2020-01-16 21:46:41,788 INFO: website startup [in /Users/wouterlefebvre/Github Repo's/FaceRec/application/__init__.py:37]
